publishDir = "docs"
title = "My Blog"
baseURL = "https://jbrandhorst.com/"
languageCode = "en-gb"
canonifyURLs = true
copyright = "Copyright (c) 2017, Johan Brandhorst; all rights reserved. Thanks to Netlify.com for hosting my blog!"

[params]
	# See themes/nofancy/static/highlight/styles for available options
	# i.e. "default", "github", "monokai".
	highlight="default"

	# Controls what items are listed in the top nav menu
	# "none", or "categories"
	# If you have too many categories to fit in the top nav menu, set this to "none"
	topmenu="categories"

[author]
    name = "Johan Brandhorst"
    github = "johanbrandhorst"
    linkedin = "johan-brandhorst-satzkorn-aa318220"
    facebook = "johan.brandhorst"
    gaID = "UA-96154465-1"
    twitter = "JohanBrandhorst"
