[build]
command = "hugo"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_VERSION = "0.128.2"

[context.deploy-preview]
command = "hugo -b $DEPLOY_PRIME_URL"

[context.deploy-preview.environment]
HUGO_VERSION = "0.128.2"

[context.branch-deploy]
command = "hugo -b https://${BRANCH}.catzkorn.dev"

[context.branch-deploy.environment]
HUGO_VERSION = "0.128.2"
